framgia/fbook_android

- app/src/main/java/com/framgia/fbook/data/model/Book.kt
- app/src/main/java/com/framgia/fbook/data/model/BookType.kt
- app/src/main/java/com/framgia/fbook/data/model/Image.kt
- app/src/main/java/com/framgia/fbook/data/model/Message.kt
- app/src/main/java/com/framgia/fbook/data/model/Owner.kt
- app/src/main/java/com/framgia/fbook/data/source/HomeDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/HomeRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/HomeRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/response/BaseResponse.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/NameApi.kt
- app/src/main/java/com/framgia/fbook/utils/Constant.kt
- circle.yml
Feature Logic List Lastest Book
> [Sprint 2]Feature Logic List Lastest Book

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/fbook/screen/SearchBook/SearchBookActivity.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/SearchBookComponent.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/SearchBookContract.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/SearchBookModule.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/SearchBookPresenter.kt
- app/src/main/java/com/framgia/fbook/screen/main/MainActivity.kt
- app/src/main/java/com/framgia/fbook/utils/binding/BindingUtils.kt
- app/src/main/res/drawable-xxhdpi/md_nav_back.xml
- app/src/main/res/layout/activity_searchbook.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
>  [Sprint 3] Feature search book UI #1

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/fbook/screen/SearchBook/SearchBookActivity.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/SearchBookContainerFragment.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/SearchBookModule.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/SearchBookPagerAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/googlebook/GoogleBookComponent.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/googlebook/GoogleBookContract.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/googlebook/GoogleBookFragment.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/googlebook/GoogleBookModule.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/googlebook/GoogleBookPresenter.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/internalbook/InternalBookComponent.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/internalbook/InternalBookContract.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/internalbook/InternalBookFragment.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/internalbook/InternalBookModule.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/internalbook/InternalBookPresenter.kt
- app/src/main/res/layout/activity_searchbook.xml
- app/src/main/res/layout/fragment_googlebook.xml
- app/src/main/res/layout/fragment_internalbook.xml
- app/src/main/res/layout/fragment_seach_book_container.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
>  [Sprint 3] feature search book ui#2

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/fbook/data/source/UserDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/UserRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/UserRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/request/SignInRequest.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/response/SignInResponse.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/NameApi.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginActivity.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginContract.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginModule.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginPresenter.kt
- app/src/main/res/layout/activity_login.xml
> [Sprint 3] feature login logic #1

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/fbook/AppComponent.kt
- app/src/main/java/com/framgia/fbook/data/source/TokenDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/TokenRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/local/TokenLocalDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/local/sharedprf/SharedPrefsKey.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginActivity.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginContract.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginModule.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginPresenter.kt
Link  : https://dev.framgia.com/redmine/issues/134857
> [Sprint 3] Feature Login Logic #2

- app/build.gradle
- app/src/main/java/com/framgia/fbook/data/source/remote/api/error/BaseException.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/middleware/RxErrorHandlingCallAdapterFactory.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/response/ErrorResponse.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginActivity.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginContract.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginModule.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginPresenter.kt
- app/src/main/java/com/framgia/fbook/utils/binding/BindingUtils.kt
- app/src/main/java/com/framgia/fbook/utils/validator/ValidType.kt
- app/src/main/java/com/framgia/fbook/utils/validator/Validator.kt
- app/src/main/java/com/framgia/fbook/widget/dialog/DialogManager.kt
- app/src/main/java/com/framgia/fbook/widget/dialog/DialogManagerImpl.kt
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/values/strings.xml
- build.gradle
- dependencies.gradle
Link : https://dev.framgia.com/redmine/issues/134857
> [Sprint 3] Feature login logic #3

- app/src/main/java/com/framgia/fbook/data/source/TokenRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/UserDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/UserRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/UserRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginActivity.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginContract.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginPresenter.kt
- app/src/main/java/com/framgia/fbook/utils/navigator/Navigator.kt
- app/src/main/java/com/framgia/fbook/utils/rx/ImmediateSchedulerProvider.kt
- app/src/main/java/com/framgia/fbook/utils/validator/Validator.kt
- app/src/main/java/com/framgia/fbook/widget/dialog/DialogManagerImpl.kt
- app/src/test/java/com/framgia/fbook/screen/login/LoginPresenterTest.kt
Link : https://dev.framgia.com/redmine/issues/135060
> [Sprint 3] Feature Unit Test Login Logic

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/fbook/screen/main/MainActivity.kt
- app/src/main/java/com/framgia/fbook/screen/main/MainContainerFragment.kt
- app/src/main/java/com/framgia/fbook/screen/main/MainContainerPagerAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/main/MainModule.kt
- app/src/main/java/com/framgia/fbook/screen/mainpage/MainPageFragment.kt
- app/src/main/java/com/framgia/fbook/utils/Constant.kt
- app/src/main/java/com/framgia/fbook/utils/binding/BindingUtils.kt
- app/src/main/java/com/framgia/fbook/utils/widget/UnSwipeViewPager.kt
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_main_container.xml
Create Main Page Container
Link redmine: https://dev.framgia.com/redmine/issues/135012
> [Sprint 2] Create Main Page Container

- app/src/main/java/com/framgia/fbook/screen/main/MainContainerFragment.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookComponent.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookContract.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookFragment.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookModule.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookPresenter.kt
- app/src/main/java/com/framgia/fbook/screen/notification/NotificationComponent.kt
- app/src/main/java/com/framgia/fbook/screen/notification/NotificationContract.kt
- app/src/main/java/com/framgia/fbook/screen/notification/NotificationFragment.kt
- app/src/main/java/com/framgia/fbook/screen/notification/NotificationModule.kt
- app/src/main/java/com/framgia/fbook/screen/notification/NotificationPresenter.kt
- app/src/main/res/layout/fragment_mybook.xml
- app/src/main/res/layout/fragment_notification.xml
Link : https://dev.framgia.com/redmine/issues/135225
> [Sprint 3] Init Fragment Home

- app/src/main/java/com/framgia/fbook/screen/menuprofile/MenuProfileAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/menuprofile/MenuProfileContainerFragment.kt
- app/src/main/java/com/framgia/fbook/screen/menuprofile/MenuProfileFragment.kt
- app/src/main/java/com/framgia/fbook/screen/menuprofile/MenuProfileModule.kt
- app/src/main/res/layout/fragment_menu_profile.xml
- app/src/main/res/layout/fragment_menu_profile_container.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
UI Pesonal Information + UI Category Favorite	
Link redmine: https://dev.framgia.com/redmine/issues/135512
> [Sprint 4] Create Page Container Profile Information

- app/src/main/java/com/framgia/fbook/data/model/Book.kt
- app/src/main/java/com/framgia/fbook/data/model/User.kt
- app/src/main/java/com/framgia/fbook/data/source/TokenDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/TokenRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/UserDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/UserRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/local/TokenLocalDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/local/UserLocalDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/local/sharedprf/SharedPrefsKey.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/UserRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/response/BaseResponse.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/NameApi.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginActivity.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginContract.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginModule.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginPresenter.kt
- app/src/test/java/com/framgia/fbook/screen/login/LoginPresenterTest.kt
Link : https://dev.framgia.com/redmine/issues/135807
> [Sprint 3] Feature get user profile

- app/src/main/java/com/framgia/fbook/AppComponent.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/BaseRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/BookRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/HomeRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/UserRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/NetworkModule.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/SearchBookComponent.kt
Link: https://dev.framgia.com/redmine/issues/135930
> [Sprint 3] Feature rename nameapi to fbookapi

- app/src/main/java/com/framgia/fbook/data/source/BookDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/BookRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/BookRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/main/MainComponent.kt
- app/src/main/java/com/framgia/fbook/screen/main/MainContainerFragment.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookContract.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookFragment.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookModule.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookPresenter.kt
- app/src/main/res/layout/fragment_mybook.xml
- app/src/main/res/layout/item_list_my_book.xml
- https://dev.framgia.com/redmine/issues/135922
- Feature my book logic #1
> [Sprint 3] Feature my book logic  #1

- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/CategoryFavoriteComponent.kt
- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/CategoryFavoriteContract.kt
- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/CategoryFavoriteFragment.kt
- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/CategoryFavoriteModule.kt
- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/CategoryFavoritePresenter.kt
- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/ItemCategoryFavoriteViewModel.kt
- app/src/main/java/com/framgia/fbook/screen/menuprofile/MenuProfileContainerFragment.kt
- app/src/main/res/layout/fragment_category_favorite.xml
- app/src/main/res/layout/item_list_category_favorite.xml
Link redmine: https://dev.framgia.com/redmine/issues/135512
[Sprint 3] UI Pesonal Information + UI Category Favorite
> [Sprint 3] Create UI Category Favorites User

- app/src/main/java/com/framgia/fbook/data/source/BookDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/BookRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/UserDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/UserRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/local/UserLocalDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/BookRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/UserRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginPresenter.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookContract.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookFragment.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookModule.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookPresenter.kt
Link: https://dev.framgia.com/redmine/issues/136211
> [Sprint 3] Feature fix my book

- app/src/main/java/com/framgia/fbook/data/source/BookDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/BookRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/BookRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/googlebook/GoogleBookFragment.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/googlebook/GoogleBookPresenter.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/internalbook/InternalBookFragment.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/internalbook/InternalBookPresenter.kt
- app/src/test/java/com/framgia/fbook/screen/SearchBook/googlebook/GoogleBookPresenterTest.kt
- app/src/test/java/com/framgia/fbook/screen/SearchBook/internalbook/InternalBookPresenterTest.kt
Link :  https://dev.framgia.com/redmine/issues/136166
> [Sprint 3] Feature search book witch google api logic unit test

- app/build.gradle
- app/src/main/java/com/framgia/fbook/data/source/remote/api/request/BookRequest.kt
- app/src/main/java/com/framgia/fbook/screen/menuprofile/MenuProfileFragment.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ImageSelectedAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ItemImageSelectedListener.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ItemImageSelectedViewModel.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ShareBookActivity.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ShareBookContract.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ShareBookModule.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ShareBookPresenter.kt
- app/src/main/java/com/framgia/fbook/utils/validator/Validator.kt
- app/src/main/res/drawable/ic_cancel_black_24dp.xml
- app/src/main/res/layout/activity_sharebook.xml
- app/src/main/res/layout/item_image_selected.xml
- app/src/main/res/values/strings.xml
- dependencies.gradle
Redmine https://dev.framgia.com/redmine/issues/136395
Feature add book logic
> [sprint 3] Feature add book logic

- app/src/main/java/com/framgia/fbook/data/model/Office.kt
- app/src/main/java/com/framgia/fbook/data/source/UserDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/UserRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/UserRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ShareBookActivity.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ShareBookContract.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ShareBookModule.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ShareBookPresenter.kt
- app/src/main/java/com/framgia/fbook/widget/dialog/DialogManager.kt
- app/src/main/java/com/framgia/fbook/widget/dialog/DialogManagerImpl.kt
- app/src/main/res/layout/activity_sharebook.xml
- app/src/main/res/values/strings.xml
Redmine https://dev.framgia.com/redmine/issues/136395
Feature add book logic
> [Sprint 4] Feature add book logic 2

- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookFragment.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookModule.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookPresenter.kt
- app/src/test/java/com/framgia/fbook/screen/mybook/MyBookPresenterTest.kt
> [Sprint 3] Unit test my book

- app/src/main/java/com/framgia/fbook/data/model/Category.kt
- app/src/main/java/com/framgia/fbook/data/source/CategoryDateSource.kt
- app/src/main/java/com/framgia/fbook/data/source/CategoryRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/CategoryRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/CategoryAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/CategoryFavoriteContract.kt
- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/CategoryFavoriteFragment.kt
- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/CategoryFavoriteModule.kt
- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/CategoryFavoritePresenter.kt
- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/ItemCategoryFavoriteViewModel.kt
- app/src/main/res/layout/fragment_category_favorite.xml
- app/src/main/res/layout/item_list_category_favorite.xml
- app/src/main/res/values/colors.xml
Task: Logic Profile
Link redmine: https://dev.framgia.com/redmine/issues/135500
> [Sprint 5] Get List Category

- app/build.gradle
- app/src/main/java/com/framgia/fbook/data/model/OfficesAndCategories.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ShareBookActivity.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ShareBookContract.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ShareBookModule.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ShareBookPresenter.kt
- app/src/main/java/com/framgia/fbook/utils/common/DateTimeUtils.kt
- app/src/main/java/com/framgia/fbook/widget/dialog/DialogManager.kt
- app/src/main/java/com/framgia/fbook/widget/dialog/DialogManagerImpl.kt
- app/src/main/res/layout/activity_sharebook.xml
- app/src/main/res/values/strings.xml
Redmine https://dev.framgia.com/redmine/issues/136395
Feature add book logic
> [Sprint 4] Feature add book logic 3

- app/src/main/java/com/framgia/fbook/screen/listbookseemore/ListBookFragment.kt
- app/src/main/java/com/framgia/fbook/screen/listbookseemore/ListBookPresenter.kt
- app/src/test/java/com/framgia/fbook/screen/listbookseemore/ListBookPresenterTest.kt
Link : https://dev.framgia.com/redmine/issues/137231
> [Sprint 4]  Feature unit test list book see more

- app/src/main/java/com/framgia/fbook/screen/mainpage/MainPageFragment.kt
- app/src/main/java/com/framgia/fbook/screen/mainpage/MainPagePresenter.kt
- app/src/test/java/com/framgia/fbook/screen/mainpage/MainPagePresenterTest.kt
Link : https://dev.framgia.com/redmine/issues/137162
> [Sprint 4] Feature unit test all list book main page

- app/src/main/java/com/framgia/fbook/screen/EndlessRecyclerOnScrollListener.kt
- app/src/main/java/com/framgia/fbook/screen/listbookseemore/ListBookContract.kt
- app/src/main/java/com/framgia/fbook/screen/listbookseemore/ListBookFragment.kt
- app/src/main/java/com/framgia/fbook/screen/listbookseemore/ListBookModule.kt
- app/src/main/java/com/framgia/fbook/screen/listbookseemore/ListBookPresenter.kt
- app/src/main/java/com/framgia/fbook/screen/mainpage/MainPageFragment.kt
- app/src/main/java/com/framgia/fbook/utils/binding/BindingUtils.kt
- app/src/main/res/layout/fragment_listbook.xml
- app/src/test/java/com/framgia/fbook/screen/listbookseemore/ListBookPresenterTest.kt
Link : https://dev.framgia.com/redmine/issues/137486
> [Sprint 4]Feature add load more list book see more

- app/src/main/java/com/framgia/fbook/data/source/BookDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/BookRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/BookRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ShareBookActivity.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ShareBookContract.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ShareBookModule.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ShareBookPresenter.kt
- app/src/main/java/com/framgia/fbook/utils/RetrofitUtils.kt
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Redmine https://dev.framgia.com/redmine/issues/136395
Feature add book logic
> [Sprint5] feature add book logic 4

- app/src/main/java/com/framgia/fbook/data/model/ReadingBook.kt
- app/src/main/java/com/framgia/fbook/data/source/BookDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/BookRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/BookRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/request/ReadingBookRequest.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/bookdetail/BookDetailActivity.kt
- app/src/main/java/com/framgia/fbook/screen/bookdetail/BookDetailContract.kt
- app/src/main/java/com/framgia/fbook/screen/bookdetail/BookDetailPresenter.kt
- app/src/main/res/layout/activity_bookdetail.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/137461
- Feature book detail logic #2 
> [Sprint 4] Feature book detail logic #2

- app/src/main/java/com/framgia/fbook/data/model/ActionBookDetail.kt
- app/src/main/java/com/framgia/fbook/data/model/User.kt
- app/src/main/java/com/framgia/fbook/data/source/BookDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/BookRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/BookRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/request/ReadingOrCancelBookRequest.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/bookdetail/BookDetailActivity.kt
- app/src/main/java/com/framgia/fbook/screen/bookdetail/BookDetailContract.kt
- app/src/main/java/com/framgia/fbook/screen/bookdetail/BookDetailPresenter.kt
- app/src/main/res/layout/activity_bookdetail.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/137461
- Feature book detail logic #3
> [Sprint 4] Feature book detail logic #3

- app/src/main/java/com/framgia/fbook/screen/addCategoryFavorite/AddCategoryFavoriteActivity.kt
- app/src/main/java/com/framgia/fbook/screen/addCategoryFavorite/AddCategoryFavoriteAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/addCategoryFavorite/AddCategoryFavoriteContract.kt
- app/src/main/java/com/framgia/fbook/screen/addCategoryFavorite/AddCategoryFavoritePresenter.kt
- app/src/main/java/com/framgia/fbook/screen/addCategoryFavorite/ItemAddCategoryFavoriteViewModel.kt
- app/src/main/java/com/framgia/fbook/screen/addCategoryFavorite/ItemClickSelectCategoryListener.kt
- app/src/main/res/layout/item_add_category_favorite.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Task: Update Profile
Link redmine: https://dev.framgia.com/redmine/issues/137378
> [Sprint 5] Add Category Favorite User

- app/src/test/java/com/framgia/fbook/screen/listbookseemore/ListBookPresenterTest.kt
Link : https://dev.framgia.com/redmine/issues/138149
> [Sprint 5] Feature unit test list category

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/fbook/screen/bookdetail/BookDetailActivity.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserInBookDetailActivity.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserInBookDetailComponent.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserInBookDetailContract.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserInBookDetailModule.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserInBookDetailPresenter.kt
- app/src/main/res/layout/activity_user_in_book_detail.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/138123
- Mainpage user book detail
> [Sprint 5] Mainpage user book detail

- app/src/main/java/com/framgia/fbook/data/source/CategoryDateSource.kt
- app/src/main/java/com/framgia/fbook/data/source/CategoryRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/CategoryRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/request/AddCategoryFavoriteRequest.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/addCategoryFavorite/AddCategoryFavoriteActivity.kt
- app/src/main/java/com/framgia/fbook/screen/addCategoryFavorite/AddCategoryFavoriteContract.kt
- app/src/main/java/com/framgia/fbook/screen/addCategoryFavorite/AddCategoryFavoritePresenter.kt
- app/src/main/java/com/framgia/fbook/utils/Constant.kt
Task: Update Profile
Link redmine: https://dev.framgia.com/redmine/issues/137378
> [Sprint 5] Add Category Favorite Continue

- app/src/main/java/com/framgia/fbook/data/model/SortBook.kt
- app/src/main/java/com/framgia/fbook/data/source/BookDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/BookRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/BookRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/listbookseemore/ListBookFragment.kt
- app/src/main/res/layout/fragment_listbook.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Link : https://dev.framgia.com/redmine/issues/138226
> [Sprint 5] Feature sort ui

- app/src/main/java/com/framgia/fbook/screen/bookdetail/BookDetailActivity.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserInBookDetailActivity.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserInBookDetailAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserInBookDetailModule.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserInBookDetailPresenter.kt
- app/src/main/java/com/framgia/fbook/utils/Constant.kt
- app/src/main/res/layout/activity_bookdetail.xml
- app/src/main/res/layout/activity_user_in_book_detail.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/138123
- Feature mainpage user book detail
> [Sprint 5] Feature mainpage user book detail

- app/src/main/java/com/framgia/fbook/data/model/Sort.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/listbookseemore/ListBookContract.kt
- app/src/main/java/com/framgia/fbook/screen/listbookseemore/ListBookFragment.kt
- app/src/main/java/com/framgia/fbook/screen/listbookseemore/ListBookPresenter.kt
- app/src/main/java/com/framgia/fbook/screen/mainpage/MainPagePresenter.kt
- app/src/main/res/drawable-xxhdpi/ic_arrow_drop_down.xml
- app/src/main/res/drawable/border_background_2.xml
- app/src/main/res/layout/fragment_listbook.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Link: https://dev.framgia.com/redmine/issues/138386
> [Sprint 5] Feature sort Logic

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestActivity.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestComponent.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestContract.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestModule.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestPresenter.kt
- app/src/main/java/com/framgia/fbook/screen/menuprofile/MenuProfileFragment.kt
- app/src/main/res/layout/activity_approve_request.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Redmine https://dev.framgia.com/redmine/issues/138500
Feature approve request ui
> [Sprint 5] Feature approve request ui

- app/src/main/java/com/framgia/fbook/screen/bookdetail/BookDetailActivity.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserInBookDetailActivity.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserInBookDetailAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserInBookDetailComponent.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserReview/UserReviewComponent.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserReview/UserReviewContract.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserReview/UserReviewFragment.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserReview/UserReviewModule.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserReview/UserReviewPresenter.kt
- app/src/main/res/layout/fragment_user_review.xml
- https://dev.framgia.com/redmine/issues/138468
- Feature user review ui 
> [Sprint 5] Feature user review ui

- app/src/main/java/com/framgia/fbook/data/source/BookDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/BookRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/BookRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestActivity.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestContract.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestModule.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestPresenter.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ItemApproveRequestClickListener.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ItemApproveRequestViewModel.kt
- app/src/main/res/layout/item_approve_request.xml
> [Sprint 5] Feature approve request logic

- app/src/main/java/com/framgia/fbook/data/source/BookDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/BookRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/BookRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/EndlessRecyclerOnScrollListener.kt
- app/src/main/java/com/framgia/fbook/screen/listbookseemore/ListBookContract.kt
- app/src/main/java/com/framgia/fbook/screen/listbookseemore/ListBookFragment.kt
- app/src/main/java/com/framgia/fbook/screen/listbookseemore/ListBookPresenter.kt
- app/src/main/java/com/framgia/fbook/screen/listbookseemore/adapter/ListBookAdapter.kt
- app/src/main/res/layout/fragment_listbook.xml
- app/src/test/java/com/framgia/fbook/screen/listbookseemore/ListBookPresenterTest.kt
Link : https://dev.framgia.com/redmine/issues/138386
> [Sprint 5] Feature sort Logic #2

- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestActivity.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestModule.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestPresenter.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ItemApproveRequestViewModel.kt
- app/src/main/res/layout/activity_approve_request.xml
- app/src/main/res/layout/item_approve_request.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Redmine https://dev.framgia.com/redmine/issues/138809
Feature approve request logic 2
> [Sprint 6] Feature approve request logic 2

- app/src/main/java/com/framgia/fbook/data/model/Book.kt
- app/src/main/java/com/framgia/fbook/data/model/Category.kt
- app/src/main/java/com/framgia/fbook/data/model/User.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserReview/UserReviewAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserReview/UserReviewFragment.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserReview/UserReviewModule.kt
- app/src/main/res/layout/fragment_user_review.xml
- app/src/main/res/layout/item_list_user_review.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/138734
- Feature user review logic #1
> [Sprint 5] Feature user review logic #1

- app/src/main/java/com/framgia/fbook/data/model/Book.kt
- app/src/main/java/com/framgia/fbook/screen/mainpage/MainPageContract.kt
- app/src/main/java/com/framgia/fbook/screen/mainpage/MainPageFragment.kt
- app/src/main/java/com/framgia/fbook/screen/mainpage/MainPageModule.kt
- app/src/main/java/com/framgia/fbook/screen/mainpage/MainPagePresenter.kt
- app/src/main/java/com/framgia/fbook/screen/mainpage/adapter/MainPageAdapter.kt
- app/src/main/java/com/framgia/fbook/widget/view/ImageViewLabel.kt
- app/src/main/res/layout/fragment_mainpage_item.xml
- app/src/main/res/values-sw360dp/dimens.xml
- app/src/main/res/values-vi/strings.xml
- app/src/test/java/com/framgia/fbook/screen/mainpage/MainPagePresenterTest.kt
Link : https://dev.framgia.com/redmine/issues/138839
> [Sprint 6] Feature show branch book

- app/src/main/java/com/framgia/fbook/data/source/remote/api/request/UserApproveBookRequest.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestActivity.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ItemApproveRequestClickListener.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ItemApproveRequestViewModel.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/adapterItemofitem/ItemApproveRequestAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/adapterItemofitem/ItemOfItemApproveClickListener.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/adapterItemofitem/ItemOfItemApproveRequestViewModel.kt
- app/src/main/res/layout/item_of_item_approve_request.xml
Link : https://dev.framgia.com/redmine/issues/139289
> [Sprint 6] Feature approve book logic #2

- app/src/main/java/com/framgia/fbook/screen/menuprofile/MenuProfileFragment.kt
- app/src/main/java/com/framgia/fbook/screen/personalinfor/PersonalInforComponent.kt
- app/src/main/java/com/framgia/fbook/screen/personalinfor/PersonalInforFragment.kt
- app/src/main/java/com/framgia/fbook/screen/profile/ProfileActivity.kt
- app/src/main/java/com/framgia/fbook/screen/profile/ProfileContainerFragment.kt
- app/src/main/res/layout/activity_profile.xml
- app/src/main/res/layout/fragment_menu_profile.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
Task : Edit Profile
Link redmine: https://dev.framgia.com/redmine/issues/138406
> [Sprint 5] Fix Personal User Fragment

- app/src/main/java/com/framgia/fbook/data/source/remote/api/error/BaseException.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/middleware/RxErrorHandlingCallAdapterFactory.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/response/ErrorResponse.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserReadingWaitingReturn/ItemUserClickListener.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserReadingWaitingReturn/ItemUserViewModel.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserReadingWaitingReturn/UserReadingWaitingReturnAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserReadingWaitingReturn/UserReadingWaitingReturnFragment.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserReadingWaitingReturn/UserReadingWaitingReturnModule.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserReview/UserReviewFragment.kt
- app/src/main/res/layout/fragment_user_reading_waiting_return.xml
- app/src/main/res/layout/item_list_user_reading_waiting_return.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- https://dev.framgia.com/redmine/issues/139162
- Feature user reading waiting return #2 
> [Sprint 6] Feature user reading waiting return #2

- app/src/main/java/com/framgia/fbook/data/source/UserDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/UserRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/UserRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/request/UserApproveBookRequest.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestActivity.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestContract.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestModule.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestPresenter.kt
Link : https://dev.framgia.com/redmine/issues/139442
> [Sprint 6] Feature approve book logic #3

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/fbook/data/source/UserDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/UserRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/UserRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/ApproveDetailActivity.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/ApproveDetailComponent.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/ApproveDetailContract.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/ApproveDetailModule.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/ApproveDetailPresenter.kt
- app/src/main/res/layout/activity_approvedetail.xml
Link : https://dev.framgia.com/redmine/issues/139540
> [Sprint 6] Feature approve detail UI

- app/src/main/java/com/framgia/fbook/data/source/TokenDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/TokenRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/UserDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/UserRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/local/TokenLocalDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/TokenRemoteDatasource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/UserRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/middleware/InterceptorImpl.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/request/RefreshTokenRequest.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/response/TokenResponse.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginPresenter.kt
- app/src/test/java/com/framgia/fbook/screen/login/LoginPresenterTest.kt
- https://dev.framgia.com/redmine/issues/139547
-  Feature refresh token
-  Effect : None
> [Sprint 6] Feature refresh token

- app/src/main/java/com/framgia/fbook/data/source/UserDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/UserRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/UserRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/bookdetail/BookDetailActivity.kt
- app/src/main/java/com/framgia/fbook/screen/profile/ProfileActivity.kt
- app/src/main/java/com/framgia/fbook/screen/profile/ProfileContract.kt
- app/src/main/java/com/framgia/fbook/screen/profile/ProfileModule.kt
- app/src/main/java/com/framgia/fbook/screen/profile/ProfilePresenter.kt
- app/src/main/java/com/framgia/fbook/utils/Constant.kt
Task:  Profile Other User
Link redmine: https://dev.framgia.com/redmine/issues/139557
> [Sprint 6] Get User Other Profile

- app/src/main/java/com/framgia/fbook/AppComponent.kt
- app/src/main/java/com/framgia/fbook/ApplicationModule.kt
- app/src/main/java/com/framgia/fbook/data/source/TokenRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/TokenRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/NetworkModule.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/middleware/InterceptorImpl.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/middleware/RxErrorHandlingCallAdapterFactory.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginModule.kt
- app/src/main/res/layout/activity_user_in_book_detail.xml
- app/src/main/res/layout/fragment_user_review.xml
- app/src/main/res/layout/item_list_user_reading_waiting_return.xml
- https://dev.framgia.com/redmine/issues/139547
- Feature refresh token #2
> [Sprint 6] Feature refresh token #2

- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/ApproveDetailActivity.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/ApproveDetailContract.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/ApproveDetailModule.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/ApproveDetailOwnerAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/ApproveDetailPresenter.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/GetListUserListener.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/ItemApproveDetailOwnerViewModel.kt
- app/src/main/res/layout/activity_approvedetail.xml
- app/src/main/res/layout/item_approve_detail_owner.xml
Link : https://dev.framgia.com/redmine/issues/139739
> [Sprint 6] Feature approve detail logic

- app/src/main/java/com/framgia/fbook/data/model/User.kt
- app/src/main/java/com/framgia/fbook/screen/bookdetail/BookDetailActivity.kt
- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/CategoryFavoriteFragment.kt
- app/src/main/java/com/framgia/fbook/screen/menuprofile/MenuProfileFragment.kt
- app/src/main/java/com/framgia/fbook/screen/personalinfor/PersonalInforFragment.kt
- app/src/main/java/com/framgia/fbook/screen/profile/GetUserListener.kt
- app/src/main/java/com/framgia/fbook/screen/profile/ProfileActivity.kt
- app/src/main/java/com/framgia/fbook/widget/dialog/DialogManagerImpl.kt
- app/src/main/res/layout/fragment_menu_profile.xml
[Sprint 6] Get User Other Profile
Link redmine: https://dev.framgia.com/redmine/issues/139434
> [Sprint 6] Get Personal Other User

- app/src/main/java/com/framgia/fbook/data/model/Follow.kt
- app/src/main/java/com/framgia/fbook/data/source/UserDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/UserRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/UserRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/profile/ProfileActivity.kt
- app/src/main/java/com/framgia/fbook/screen/profile/ProfileContract.kt
- app/src/main/java/com/framgia/fbook/screen/profile/ProfilePresenter.kt
Task: Button Follow User Other
Link redmine: https://dev.framgia.com/redmine/issues/139557
> Logic button follow user other

- app/src/main/java/com/framgia/fbook/data/source/BookDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/BookRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/BookRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/utils/Constant.kt
Task : Feature Other In User
Link redmine: https://dev.framgia.com/redmine/issues/140237
> [Sprint 6] Logic List Feature Other In User

- app/src/main/java/com/framgia/fbook/screen/addCategoryFavorite/AddCategoryFavoriteActivity.kt
- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/CategoryFavoriteContract.kt
- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/CategoryFavoriteFragment.kt
- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/CategoryFavoriteModule.kt
- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/CategoryFavoritePresenter.kt
- app/src/main/java/com/framgia/fbook/utils/Constant.kt
Task: Update Category Favorite User
Link redmine: https://dev.framgia.com/redmine/issues/140274
> [Sprint 6] Update Category Favorite User

- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/ApproveDetailActivity.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/GetListUserListener.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/adapterlistrequest/ItemListRequestViewModel.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/adapterlistrequest/ListRequestAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/returningandreturnedRequest/ReturningAndReturnedFragmentFragment.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/waitandreadrequest/WaitAndReadRequestFragment.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/waitandreadrequest/WaitAndReadRequestModule.kt
- app/src/main/res/layout/fragment_waitandreadrequest.xml
- app/src/main/res/layout/item_approve_request.xml
- app/src/main/res/layout/item_list_request.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Link : https://dev.framgia.com/redmine/issues/140264
> [Sprint 6] Feature approve detail logic #2

- app/src/main/java/com/framgia/fbook/screen/otheruser/OtherUserAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/BookInUserComponent.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/BookInUserContract.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/BookInUserFragment.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/BookInUserModule.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/BookInUserPresenter.kt
- app/src/main/java/com/framgia/fbook/utils/Constant.kt
- app/src/main/res/layout/fragment_book_in_user.xml
Task : Logic Book In User Profile
Link redmine: https://dev.framgia.com/redmine/issues/140237
> [Sprint 6] Logic Book In User Profile

- app/src/main/java/com/framgia/fbook/widget/view/ImageViewLabel.kt
- app/src/main/res/layout/activity_bookdetail.xml
- app/src/main/res/layout/fragment_listbook_item.xml
- app/src/main/res/layout/fragment_mainpage_item.xml
- app/src/main/res/values/dimens.xml
Link : https://dev.framgia.com/redmine/issues/140399
> [Sprint 7] feature edit image view label

- app/src/main/java/com/framgia/fbook/data/model/Notification.kt
- app/src/main/java/com/framgia/fbook/data/source/UserDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/UserRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/UserRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/response/NotificationResponse.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/notification/NotificationModule.kt
- app/src/main/java/com/framgia/fbook/screen/notification/NotificationPresenter.kt
Link : https://dev.framgia.com/redmine/issues/140463
> [Sprint 7] Feature notification ui

- app/src/main/java/com/framgia/fbook/screen/main/MainContainerFragment.kt
- app/src/main/java/com/framgia/fbook/screen/notification/NotificationContainerAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/notification/NotificationContainerFragment.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationUser/NotificationComponent.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationUser/NotificationContract.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationUser/NotificationFragment.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationUser/NotificationModule.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationUser/NotificationPresenter.kt
- app/src/main/java/com/framgia/fbook/utils/Constant.kt
- app/src/main/res/layout/fragment_notification.xml
- app/src/main/res/layout/fragment_notificationcontainer.xml
- app/src/main/res/values/strings.xml
Link : https://dev.framgia.com/redmine/issues/140726
> [Sprint 7] Feature notification Logic #2

- app/src/main/java/com/framgia/fbook/screen/listbookseemore/ListBookFragment.kt
- app/src/main/java/com/framgia/fbook/screen/listbookseemore/ListBookModule.kt
- app/src/main/java/com/framgia/fbook/screen/main/MainActivity.kt
- app/src/main/java/com/framgia/fbook/screen/main/MainModule.kt
- app/src/main/java/com/framgia/fbook/screen/mainpage/MainPageFragment.kt
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_searchbook.xml
- app/src/main/res/layout/fragment_listbook.xml
- app/src/main/res/layout/fragment_listbook_item.xml
- app/src/main/res/layout/fragment_mainpage_item.xml
- app/src/main/res/layout/item_approve_request.xml
- app/src/main/res/layout/item_list_my_book.xml
- app/src/main/res/layout/item_list_user_review.xml
- app/src/main/res/values/styles.xml
- Fix mainpage ui, item list book ui
> [Sprint 6] Fix mainpage ui, item list book ui

- app/src/main/java/com/framgia/fbook/data/source/remote/BookRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/utils/RetrofitUtils.kt
- app/src/main/res/layout/activity_sharebook.xml
- Feature Add book logic
- https://dev.framgia.com/redmine/issues/136395
> [Sprint 6] Feature Add book logic

- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/CategoryFavoriteFragment.kt
- app/src/main/java/com/framgia/fbook/screen/profile/ProfileActivity.kt
- app/src/main/res/layout/fragment_category_favorite.xml
Task: Fix Button Follow & Profile (User + Other User)
Link redmine: https://dev.framgia.com/redmine/issues/140980
> Fix Button Follow & Profile (User + Other User)

- app/src/main/java/com/framgia/fbook/data/source/remote/BookRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/utils/RetrofitUtils.kt
- Fix add book logic
https://dev.framgia.com/redmine/issues/136395
> [Sprint 6] Fix add book logic

- app/src/main/java/com/framgia/fbook/screen/main/MainActivity.kt
- app/src/main/java/com/framgia/fbook/screen/main/NotificationListener.kt
- app/src/main/java/com/framgia/fbook/screen/notification/NotificationContainerAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationFollow/NotificationFollowComponent.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationFollow/NotificationFollowContract.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationFollow/NotificationFollowFragment.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationFollow/NotificationFollowListener.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationFollow/NotificationFollowModule.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationFollow/NotificationFollowPresenter.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationUser/NotificationFragment.kt
- app/src/main/res/layout/fragment_notificationfollow.xml
Link: https://dev.framgia.com/redmine/issues/140790
> [Sprint 7] Feature notification follow ui

- app/src/main/java/com/framgia/fbook/screen/otheruser/OtherUserAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/BookInUserAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/BookInUserContract.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/BookInUserFragment.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/BookInUserPresenter.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/ItemBookInUserViewModel.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/OnReturnBookListener.kt
- app/src/main/res/layout/item_book_in_user_profile.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Task : Logic Book In User Continue
Link redmine: https://dev.framgia.com/redmine/issues/140237
> [Sprint 6] Logic Book In User Continue

- app/src/main/java/com/framgia/fbook/screen/bookdetail/BookDetailActivity.kt
- app/src/main/java/com/framgia/fbook/screen/main/MainActivity.kt
- app/src/main/java/com/framgia/fbook/screen/main/MainContract.kt
- app/src/main/java/com/framgia/fbook/screen/main/MainModule.kt
- app/src/main/java/com/framgia/fbook/screen/main/MainPresenter.kt
- app/src/main/java/com/framgia/fbook/utils/binding/BindingUtils.kt
- app/src/main/res/layout/activity_bookdetail.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_profile.xml
- app/src/main/res/layout/item_add_category_favorite.xml
- app/src/main/res/layout/item_list_category_favorite.xml
- app/src/main/res/layout/layout_not_loggin.xml
- Feature choose workspace default 
- https://dev.framgia.com/redmine/issues/141168
> [Sprint 7] Feature choose workspace default

- app/src/main/java/com/framgia/fbook/screen/notification/ItemNotificationViewModel.kt
- app/src/main/java/com/framgia/fbook/screen/notification/NotificationAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationFollow/NotificationFollowFragment.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationFollow/NotificationFollowModule.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationUser/NotificationFragment.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationUser/NotificationModule.kt
- app/src/main/java/com/framgia/fbook/utils/Constant.kt
- app/src/main/res/layout/fragment_notification.xml
- app/src/main/res/layout/fragment_notificationfollow.xml
- app/src/main/res/layout/item_notification.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Link : https://dev.framgia.com/redmine/issues/141205
> [Sprint 8] Feature notification follow UI #2

- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/adapterlistrequest/ItemListRequestViewModel.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/adapterlistrequest/ItemRequestClickListener.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/adapterlistrequest/ListRequestAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/returningandreturnedRequest/ReturningAndReturnedFragmentFragment.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/returningandreturnedRequest/ReturningAndReturnedFragmentModule.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/waitandreadrequest/WaitAndReadRequestContract.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/waitandreadrequest/WaitAndReadRequestFragment.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/waitandreadrequest/WaitAndReadRequestModule.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/waitandreadrequest/WaitAndReadRequestPresenter.kt
- app/src/main/java/com/framgia/fbook/utils/Constant.kt
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Link : https://dev.framgia.com/redmine/issues/141219
> [Sprint 6] Feature approve detail logic #3

- app/src/main/java/com/framgia/fbook/data/source/BookDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/BookRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/BookRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/OtherUserActivity.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/OtherUserAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/BookInUserAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/BookInUserContract.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/BookInUserFragment.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/BookInUserPresenter.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/ItemBookInUserViewModel.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/OnReturnBookListener.kt
- app/src/main/java/com/framgia/fbook/utils/Constant.kt
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Task : Logic Book In User
Link redmine: https://dev.framgia.com/redmine/issues/140237
> [Sprint 6] Logic Book In User Final

- app/src/main/java/com/framgia/fbook/screen/addCategoryFavorite/AddCategoryFavoriteActivity.kt
- app/src/main/java/com/framgia/fbook/screen/addCategoryFavorite/AddCategoryFavoritePresenter.kt
- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/CategoryFavoriteContract.kt
- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/CategoryFavoriteFragment.kt
- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/CategoryFavoritePresenter.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/BookInUserFragment.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/BookInUserPresenter.kt
- app/src/main/java/com/framgia/fbook/screen/profile/ProfileActivity.kt
- app/src/main/java/com/framgia/fbook/screen/profile/ProfilePresenter.kt
- app/src/test/java/com/framgia/fbook/screen/addCategoryFavorite/AddCategoryFavoritePresenterTest.kt
- app/src/test/java/com/framgia/fbook/screen/categoryfavorite/CategoryFavoritePresenterTest.kt
- app/src/test/java/com/framgia/fbook/screen/otheruser/bookInUser/BookInUserPresenterTest.kt
- app/src/test/java/com/framgia/fbook/screen/profile/ProfilePresenterTest.kt
Task: Unit Test Profile, Other Profile And Book In User
Link redmine: https://dev.framgia.com/redmine/issues/141351
> [Sprint 6] Write Unit Test Profile & Book In User

- app/src/main/java/com/framgia/fbook/data/source/BookDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/BookRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/CategoryDateSource.kt
- app/src/main/java/com/framgia/fbook/data/source/CategoryRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/BookRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/CategoryRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/listbookseemore/ListBookContract.kt
- app/src/main/java/com/framgia/fbook/screen/listbookseemore/ListBookFragment.kt
- app/src/main/java/com/framgia/fbook/screen/listbookseemore/ListBookModule.kt
- app/src/main/java/com/framgia/fbook/screen/listbookseemore/ListBookPresenter.kt
- app/src/main/java/com/framgia/fbook/screen/main/MainActivity.kt
- app/src/main/java/com/framgia/fbook/screen/mainpage/MainPageContract.kt
- app/src/main/java/com/framgia/fbook/screen/mainpage/MainPageFragment.kt
- app/src/main/java/com/framgia/fbook/screen/mainpage/MainPagePresenter.kt
- app/src/main/java/com/framgia/fbook/screen/mainpage/adapter/MainPageAdapter.kt
- Feature choose workspace #2
- https://dev.framgia.com/redmine/issues/141168
> [Sprint 7] Feature choose workspace #2

- app/src/main/java/com/framgia/fbook/screen/main/MainActivity.kt
- app/src/main/java/com/framgia/fbook/screen/main/NotificationListener.kt
- app/src/main/java/com/framgia/fbook/screen/notification/ItemNotificationViewModel.kt
- app/src/main/java/com/framgia/fbook/screen/notification/NotificationContainerFragment.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationUser/NotificationFragment.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationUser/NotificationUserListener.kt
- app/src/main/res/layout/fragment_notification.xml
- app/src/main/res/layout/fragment_notificationcontainer.xml
- app/src/main/res/layout/item_notification.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Link : https://dev.framgia.com/redmine/issues/141352
> [Sprint 8] Feature notification logic #3

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/fbook/fireBase/FireBaseComponent.kt
- app/src/main/java/com/framgia/fbook/fireBase/FireBaseInstanceIDService.kt
- app/src/main/java/com/framgia/fbook/fireBase/FireBaseMessageService.kt
- app/src/main/java/com/framgia/fbook/fireBase/FireBaseModule.kt
- app/src/main/java/com/framgia/fbook/utils/dagger/ServiceScope.kt
- build.gradle
- dependencies.gradle
- Feature notification firebase 
- https://dev.framgia.com/redmine/issues/141461
> [Sprint 7] Feature notification firebase

- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/ApproveDetailActivity.kt
- app/src/main/res/layout/activity_approvedetail.xml
- app/src/main/res/layout/fragment_main_page.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
> [Sprint 7] Fix Approve book detail ui

- app/src/main/java/com/framgia/fbook/data/source/remote/api/response/CountNotification.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/internalbook/InternalBookFragment.kt
- app/src/main/java/com/framgia/fbook/screen/bookdetail/BookDetailActivity.kt
- app/src/main/java/com/framgia/fbook/screen/listbookseemore/ListBookFragment.kt
- app/src/main/java/com/framgia/fbook/screen/mainpage/MainPageFragment.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookFragment.kt
- app/src/main/java/com/framgia/fbook/screen/notification/ItemNotificationViewModel.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationFollow/NotificationFollowFragment.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationFollow/NotificationFollowModule.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationUser/NotificationFragment.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/BookInUserFragment.kt
Link : https://dev.framgia.com/redmine/issues/141513
> [Sprint 8] Feature notification logic #4

- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/ApproveDetailActivity.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/ApproveDetailOwnerAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/ItemApproveDetailOwnerViewModel.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/adapterlistrequest/ItemListRequestViewModel.kt
- app/src/main/res/drawable/button_click_red.xml
- app/src/main/res/layout/item_list_request.xml
- app/src/main/res/values/strings.xml
Fix Ui Approve Detail
Effect : None
> Fix Ui Approve Detail

- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/adapterlistrequest/ItemListRequestViewModel.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/adapterlistrequest/ListRequestAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/returningandreturnedRequest/ReturningAndReturnedFragmentContract.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/returningandreturnedRequest/ReturningAndReturnedFragmentFragment.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/returningandreturnedRequest/ReturningAndReturnedFragmentModule.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/returningandreturnedRequest/ReturningAndReturnedFragmentPresenter.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/waitandreadrequest/WaitAndReadRequestFragment.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/waitandreadrequest/WaitAndReadRequestModule.kt
- app/src/main/res/layout/fragment_returningandreturnedfragment.xml
Link : https://dev.framgia.com/redmine/issues/141569
> [Sprint 8] Feature approve detail logic #4

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/framgia/fbook/MainApplication.kt
- dependencies.gradle
- Feature config pusher notification
- https://dev.framgia.com/redmine/issues/141461
> [Sprint 7] Feature config pusher notification

- app/src/main/java/com/framgia/fbook/data/source/UserDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/UserRepository.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/UserRemoteDataSource.kt
- app/src/main/java/com/framgia/fbook/data/source/remote/api/service/FBookApi.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationFollow/NotificationFollowContract.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationFollow/NotificationFollowFragment.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationFollow/NotificationFollowModule.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationFollow/NotificationFollowPresenter.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationUser/NotificationContract.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationUser/NotificationFragment.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationUser/NotificationPresenter.kt
Link : https://dev.framgia.com/redmine/issues/141817
> [Sprint 8] Feature click notification logic 

- app/src/main/java/com/framgia/fbook/screen/mainpage/adapter/MainPageAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/ItemMyBookClickListener.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/ItemMyBookViewModel.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookFragment.kt
- app/src/main/res/drawable-xxhdpi/ic_place.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_listbook.xml
- app/src/main/res/layout/fragment_listbook_item.xml
- app/src/main/res/layout/fragment_mainpage_item.xml
- app/src/main/res/layout/item_approve_request.xml
- app/src/main/res/layout/item_list_my_book.xml
> [Sprint 7] Fix mainpage ui #4

- app/src/main/java/com/framgia/fbook/data/model/Book.kt
- app/src/main/java/com/framgia/fbook/screen/main/MainActivity.kt
- app/src/main/java/com/framgia/fbook/screen/main/NotificationListener.kt
- app/src/main/java/com/framgia/fbook/screen/notification/ItemNotificationClickListener.kt
- app/src/main/java/com/framgia/fbook/screen/notification/ItemNotificationViewModel.kt
- app/src/main/java/com/framgia/fbook/screen/notification/NotificationAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationFollow/NotificationFollowFragment.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationUser/NotificationFragment.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ShareBookActivity.kt
- app/src/main/res/layout/activity_sharebook.xml
Link : https://dev.framgia.com/redmine/issues/141866
> [Sprint 8] Feature click notification logic #2

- app/src/main/java/com/framgia/fbook/screen/addCategoryFavorite/AddCategoryFavoriteActivity.kt
- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/CategoryFavoriteFragment.kt
- app/src/main/java/com/framgia/fbook/screen/categoryfavorite/CategoryFavoriteModule.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginActivity.kt
- app/src/main/java/com/framgia/fbook/screen/menuprofile/MenuProfileFragment.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ShareBookActivity.kt
- app/src/main/java/com/framgia/fbook/widget/dialog/DialogManager.kt
- app/src/main/java/com/framgia/fbook/widget/dialog/DialogManagerImpl.kt
- app/src/main/res/layout/activity_sharebook.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Add SnackBar & Fix Update Category User
Effect : None
> Add SnackBar & Fix Update Category User

- app/src/main/java/com/framgia/fbook/screen/main/MainActivity.kt
- app/src/main/java/com/framgia/fbook/screen/main/NotificationListener.kt
- app/src/main/java/com/framgia/fbook/screen/menuprofile/MenuProfileFragment.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookContract.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookFragment.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookPresenter.kt
- app/src/main/java/com/framgia/fbook/screen/notification/NotificationContainerFragment.kt
- app/src/main/java/com/framgia/fbook/utils/binding/BindingUtils.kt
- app/src/main/res/layout/fragment_mybook.xml
Link : https://dev.framgia.com/redmine/issues/142058
> [Sprint Maintain] Feature add refresh layout my book and fix count notification

- app/src/main/java/com/framgia/fbook/screen/sharebook/ShareBookActivity.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ShareBookModule.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ShareBookPresenter.kt
- app/src/test/java/com/framgia/fbook/screen/sharebook/ShareBookPresenterTest.kt
- build.gradle
> Unit Test Share Book

- app/google-services.json
- app/src/main/java/com/framgia/fbook/data/model/Book.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestActivity.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ItemApproveRequestClickListener.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ItemApproveRequestViewModel.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/waitandreadrequest/WaitAndReadRequestFragment.kt
- app/src/main/java/com/framgia/fbook/utils/Constant.kt
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/item_notification.xml
-  Fix ui mainpage, fix approve request logic
-  Effec : None
> [Sprint 9] Fix ui mainpage, fix approve request logic

- app/src/test/java/com/framgia/fbook/screen/listbookseemore/ListBookPresenterTest.kt
- app/src/test/java/com/framgia/fbook/screen/mainpage/MainPagePresenterTest.kt
> Feature fix unit test

- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ItemApproveRequestViewModel.kt
- app/src/main/java/com/framgia/fbook/screen/main/MainActivity.kt
- app/src/main/java/com/framgia/fbook/screen/mainpage/MainPageFragment.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/BookInUserFragment.kt
- app/src/main/java/com/framgia/fbook/utils/Constant.kt
- app/src/main/res/drawable/ic_bookmark.xml
- app/src/main/res/layout/fragment_main_page.xml
- app/src/main/res/layout/item_approve_request.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Add SnackBar And Fix Approve Book
Effect : None
> Add SnackBar And Fix Approve Book

- app/src/main/res/layout/activity_login.xml
- app/src/main/res/values-vi/strings.xml
Add Text Translate VietNamese
Effect: None
> Add Text Translate VietNamese

- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestActivity.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestAdapter.kt
- app/src/main/res/layout/fragment_googlebook.xml
- app/src/main/res/layout/fragment_internalbook.xml
Link: https://dev.framgia.com/redmine/issues/142121
> [Sprint Maintain] Feature fix search book ui and sort approve request

- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestActivity.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestContract.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestPresenter.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationUser/NotificationContract.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationUser/NotificationFragment.kt
- app/src/main/java/com/framgia/fbook/screen/notification/notificationUser/NotificationPresenter.kt
- app/src/main/res/layout/activity_approve_request.xml
- app/src/main/res/layout/fragment_notification.xml
Add Swipe Refresh Screen Approve Request & Notification
Effect: None
> Add Swipe Refresh Screen Approve Request & Notification

- app/src/main/java/com/framgia/fbook/screen/addCategoryFavorite/AddCategoryFavoriteActivity.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/BookInUserContract.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/BookInUserFragment.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/BookInUserPresenter.kt
- app/src/main/res/layout/activity_book_see_more.xml
- app/src/main/res/layout/fragment_book_in_user.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Add Swipe Refresh Layout Book In User
Effect: None
+ Thêm swipe refresh cho màn hình book in user (load lại dữ liệu)
> Add Swipe Refresh Layout Book In User

- app/src/main/res/layout/activity_book_see_more.xml
Remove Swipe List Shop More
Link redmine: https://dev.framgia.com/redmine/issues/142897
Xoá swipe trong list shop more vì không cần thiết ở màn hình này
> Remove Swipe List Shop More

- app/build.gradle
- app/google-services.json
- app/src/main/java/com/framgia/fbook/MainApplication.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/googlebook/GoogleBookFragment.kt
- app/src/main/java/com/framgia/fbook/screen/SearchBook/internalbook/InternalBookFragment.kt
- app/src/main/res/layout/fragment_googlebook.xml
- app/src/main/res/layout/fragment_internalbook.xml
Link : https://dev.framgia.com/redmine/issues/142907,https://dev.framgia.com/redmine/issues/142121
> [Sprint Maintain] Feature config pusher and fix search UI

- app/src/main/java/com/framgia/fbook/screen/bookseemore/BookSeeMoreActivity.kt
Link : https://dev.framgia.com/redmine/issues/143150
> [Sprint Maintain] Feature fix load more category

- app/src/main/java/com/framgia/fbook/screen/approverequest/ApproveRequestActivity.kt
- app/src/main/java/com/framgia/fbook/screen/approverequest/approvedetail/ApproveDetailActivity.kt
- app/src/main/java/com/framgia/fbook/screen/bookdetail/BookDetailActivity.kt
- app/src/main/java/com/framgia/fbook/screen/bookseemore/BookSeeMoreActivity.kt
- app/src/main/java/com/framgia/fbook/screen/login/LoginActivity.kt
- app/src/main/java/com/framgia/fbook/screen/main/MainActivity.kt
- app/src/main/java/com/framgia/fbook/screen/profile/ProfileActivity.kt
- app/src/main/java/com/framgia/fbook/screen/sharebook/ShareBookActivity.kt
- app/src/main/java/com/framgia/fbook/utils/Constant.kt
- app/src/main/java/com/framgia/fbook/widget/dialog/DialogManagerImpl.kt
Link : https://dev.framgia.com/redmine/issues/143265
> [Sprint Maintain] Feature fix dialog and add animation when finish activity

- app/src/main/java/com/framgia/fbook/screen/bookdetail/BookDetailActivity.kt
- app/src/main/java/com/framgia/fbook/screen/userinbookdetail/UserInBookDetailActivity.kt
- app/src/main/java/com/framgia/fbook/utils/Constant.kt
- app/src/main/res/layout/activity_bookdetail.xml
- app/src/main/res/layout/activity_user_in_book_detail.xml
Link : https://dev.framgia.com/redmine/issues/143382
> [Sprint Maintain] Feature fix book detail

- app/src/main/java/com/framgia/fbook/screen/main/LoginListener.kt
- app/src/main/java/com/framgia/fbook/screen/main/MainActivity.kt
- app/src/main/java/com/framgia/fbook/screen/menuprofile/MenuProfileFragment.kt
- app/src/main/java/com/framgia/fbook/screen/mybook/MyBookFragment.kt
- app/src/main/java/com/framgia/fbook/screen/notification/NotificationContainerFragment.kt
Link : https://dev.framgia.com/redmine/issues/143625
> [Sprint Maintain] Feature fix visible not login

- app/src/main/java/com/framgia/fbook/data/model/BookInUser.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/OtherUserAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/profile/ProfileActivity.kt
- app/src/main/java/com/framgia/fbook/screen/profile/ProfileContract.kt
- app/src/main/java/com/framgia/fbook/screen/profile/ProfileModule.kt
- app/src/main/java/com/framgia/fbook/screen/profile/ProfilePresenter.kt
- app/src/main/java/com/framgia/fbook/utils/Constant.kt
- app/src/main/res/drawable/button_click_blue.xml
- app/src/main/res/drawable/button_green_follow.xml
- app/src/main/res/layout/activity_bookdetail.xml
- app/src/main/res/layout/activity_other_user.xml
- app/src/main/res/layout/activity_profile.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Link redmine: https://dev.framgia.com/redmine/issues/143500
Chỉnh sửa lại bố cục của màn hình thông tin người dùng
> Fix UI Profile

- app/src/main/java/com/framgia/fbook/screen/bookseemore/BookSeeMoreActivity.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/OtherUserActivity.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/OtherUserAdapter.kt
- app/src/main/java/com/framgia/fbook/screen/otheruser/bookInUser/ItemBookInUserViewModel.kt
- app/src/main/java/com/framgia/fbook/screen/profile/ProfileActivity.kt
- app/src/main/java/com/framgia/fbook/screen/profile/ProfileContract.kt
- app/src/main/java/com/framgia/fbook/screen/profile/ProfilePresenter.kt
- app/src/main/java/com/framgia/fbook/utils/Constant.kt
- app/src/main/res/layout/activity_other_user.xml
- app/src/main/res/layout/activity_profile.xml
- app/src/main/res/layout/book_see_more_item.xml
Fix Proifile
Link redmine:  https://dev.framgia.com/redmine/issues/143500
> Fix Proifile

- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
Fix Language
https://dev.framgia.com/redmine/issues/144119
> Fix Language

- app/src/main/java/com/framgia/fbook/screen/bookdetail/BookDetailActivity.kt
- app/src/main/res/layout/activity_sharebook.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- circle.yml
Fix Suggest Text 
Edit  : Are you sure add owner this book? => Are you sure you want to share this book?
> Fix Suggest Text
